import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import { MenubarDemo } from "@/components/root/ServerRootLayouts";
import { Providers } from "./providers";
import { ThemeSwitcher } from "@/components/root/ClientRootLayouts";

const inter = Lora({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased h-[100vh] dark:bg-background`}
      >
        <Providers>
          <MenubarDemo />
          {children}
          <div className="flex items-center space-x-2 fixed bottom-0 right-0 p-4">
            <ThemeSwitcher />
          </div>
        </Providers>
      </body>
    </html>
  );
}

// import localFont from "next/font/local";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
